FROM mcr.microsoft.com/playwright/dotnet:v1.54.0-jammy AS build
WORKDIR /app

# Copier csproj et restaurer
COPY *.csproj ./
RUN dotnet restore

# Copier le reste et publier
COPY . ./
RUN dotnet publish -c Release -o out

# Runtime
FROM mcr.microsoft.com/playwright/dotnet:v1.54.0-jammy
WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "BingSearch.dll"]
